### ISSUE TITLE
Dependency on Angular Material

### ISSUE THREAD

**Issue by funkytaco** [planet-training/material-design-icons#2]
Hi,

I'm using Semantic UI and not Angular material, but I want to use the material design icons in an Angular-Meteor project. It seems I must include ngMaterial for it to work.

Here's my app.js

```
angular.module('myapp', [
  'angular-meteor',
  'ui.router',
    'ngMaterial'

]);

var themeIcons = ['$mdIconProvider' , function ($mdIconProvider) {

  $mdIconProvider
    .iconSet("social", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-social.svg")
    .iconSet("action", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-action.svg")
    .iconSet("communication", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-communication.svg")
    .iconSet("content", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-content.svg")
    .iconSet("toggle", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-toggle.svg")
    .iconSet("navigation", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-navigation.svg")
    .iconSet("image", "/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-image.svg");

}];

angular.module('myapp')
  .config(themeIcons);

function onReady() {
  angular.bootstrap(document, ['myapp']);
}

if (Meteor.isCordova)
  angular.element(document).on("deviceready", onReady);
else
  angular.element(document).ready(onReady);
```

In summary: I'd like to use this Meteor package
https://atmospherejs.com/planettraining/material-design-icons

without depending on this one:
https://atmospherejs.com/angular/angular-material

**Comment by dohomi** [comment]
Hi @funkytaco 

we don't have any dependency on angular material, you can see it here: https://github.com/planet-training/material-design-icons/blob/master/package.js

All what this package does is to add the sprite images into your app. The instructions above just shows how to add the iconSet into your app with the angular material package included. Please post your instructions for the SemanticUI framework here and I'll add it into the `README`as well.

**Comment by dohomi** [comment]
I'll close this issue, please let me know if you still bump into any issue

**Comment by funkytaco** [comment]
Maybe this is a dependency of https://github.com/Urigo/angular-meteor. I will check with them, as I definitely couldn't get it working without the ngMaterial dependency line.
