### ISSUE TITLE
there are more icon sprites available, check out the material-design-icons page

### ISSUE THREAD

**Issue by 6gsaifulislam** [planet-training/material-design-icons#3]
Could you give a full list of the icon files available on bower - I do not know how to get at the list to look myself  (I am trying to use the icon hardware section).

**Comment by mxab** [comment]
Does this help you? https://www.google.com/design/icons/

If you select one of the icons you'll see the id in url after the hash. Then it is usually "ID_24px"
For example:
url: https://www.google.com/design/icons/#ic_computer

so you would use this in the svg icon part: "ic_computer_24px"

**Comment by 6gsaifulislam** [comment]
@mxab Many thanks
