### ISSUE TITLE
Not All ICONS are available

### ISSUE THREAD

**Issue by denwill** [planet-training/material-design-icons#6]
How do I see the all ICONS available within the package.  

When I try to use the icons from Google Material Design site, most of them are not available in the Sprite ICON sets. For example communication:ic_comment_24px.svg does not work in Meteor apps.

**Comment by dohomi** [comment]
Hi @denwill 

please check this repository: 

https://github.com/planet-training/material-design-icons-font

Its currently the better approach for the app and there it should work without problem

**Comment by mxab** [comment]
you can also clone the orignal repository 

```
git clone https://github.com/google/material-design-icons.git
cd material-design-icons/sprites/svg-sprite/
python -m SimpleHTTPServer 5555
```

Then browse the html files in http://localhost:5555

**Comment by denwill** [comment]
Thanks guys,

Icons fonts does not work very well with FAB Toolbar, the SVG Icons sets works well.
